version: '3' 
networks:
  default:
    name:
      global_network
  maria-network:
    driver: bridge
    ipam: 
      config: 
       - subnet: 192.168.10.0/16
services:
  node0:
    image: mariadb:10.5.11-focal
    container_name: node0
    hostname: node0
    environment:
#      MYSQL_ROOT_PASSWORD: root_P@ssw0rd
      TZ: Asia/Bangkok
      MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP: 1
#      MYSQL_USER: haproxy
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: always 
    volumes: 
       - ./conf.d/mariaDB/galera-node0.cnf:/etc/mysql/conf.d/galera.cnf  
       - ./data/node0/mysql:/var/lib/mysql
#       - ./conf.d/mariaDB-encryption/keyfile.enc:/etc/mysql/encryption/keyfile.enc
#       - ./conf.d/mariaDB-encryption/.keyfile.key:/etc/mysql/encryption/.keyfile.key
       - ./conf.d/mariaDB-ssl/ca.pem:/etc/ssl/galera/ca.pem
       - ./conf.d/mariaDB-ssl/tls.key:/etc/ssl/galera/tls.key
       - ./conf.d/mariaDB-ssl/tls.crt:/etc/ssl/galera/tls.crt
    command: --wsrep-new-cluster 
    networks:
      maria-network:
        ipv4_address: 192.168.10.10
  node1:
    image: mariadb:10.5.11-focal
    container_name: node1
    hostname: node1
    environment:
#      MYSQL_ROOT_PASSWORD: root_P@ssw0rd
      TZ: Asia/Bangkok
#      MYSQL_USER: haproxy
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: always
    volumes:
      - ./conf.d/mariaDB/galera-node1.cnf:/etc/mysql/conf.d/galera.cnf
      - ./data/node1/mysql:/var/lib/mysql
#      - ./conf.d/mariaDB-encryption/keyfile.enc:/etc/mysql/encryption/keyfile.enc
#      - ./conf.d/mariaDB-encryption/.keyfile.key:/etc/mysql/encryption/.keyfile.key
      - ./conf.d/mariaDB-ssl/ca.pem:/etc/ssl/galera/ca.pem
      - ./conf.d/mariaDB-ssl/tls.key:/etc/ssl/galera/tls.key
      - ./conf.d/mariaDB-ssl/tls.crt:/etc/ssl/galera/tls.crt
    networks:
      maria-network:
        ipv4_address: 192.168.10.11
  node2:
    image: mariadb:10.5.11-focal
    container_name: node2
    hostname: node2
    environment:
#      MYSQL_ROOT_PASSWORD: root_P@ssw0rd
      TZ: Asia/Bangkok
#      MYSQL_USER: haproxy
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - ./conf.d/mariaDB/galera-node2.cnf:/etc/mysql/conf.d/galera.cnf
      - ./data/node2/mysql:/var/lib/mysql
#      - ./conf.d/mariaDB-encryption/keyfile.enc:/etc/mysql/encryption/keyfile.enc
#      - ./conf.d/mariaDB-encryption/.keyfile.key:/etc/mysql/encryption/.keyfile.key
      - ./conf.d/mariaDB-ssl/ca.pem:/etc/ssl/galera/ca.pem
      - ./conf.d/mariaDB-ssl/tls.key:/etc/ssl/galera/tls.key
      - ./conf.d/mariaDB-ssl/tls.crt:/etc/ssl/galera/tls.crt
    networks:
      maria-network:
        ipv4_address: 192.168.10.12

  haproxy:
    image: haproxy:2.4.2 
    container_name: haproxy
    hostname: haproxy
    environment:
      DB0_ADDRESS: 192.168.10.10
      DB1_ADDRESS: 192.168.10.11
      DB2_ADDRESS: 192.168.10.12
      DB0_PORT: 3306
      DB1_PORT: 3306
      DB2_PORT: 3306
    restart: always
    ports:
      - 8080:9000 
    volumes:
      - ./conf.d/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      maria-network:
        ipv4_address: 192.168.10.13
#  wordpress:
#    depends_on:
#      - node2
#    image: wordpress:latest
#    volumes:
#      - ./data/wordpress:/var/www/html
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: node2
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#    networks:
#      maria-network:
#        ipv4_address: 192.168.10.14
 
  ubunru:
    image: ubuntu:latest
    restart: always
    environment:
      LANG: C.UTF-8
    entrypoint:  
      - bash
    tty: true
    networks:
      maria-network:
        ipv4_address: 192.168.10.15
 
